// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIxdIByssf5hkdxvDfeTz6todXh4zk58',
    appId: '1:973797524907:web:659918136353d52d637eee',
    messagingSenderId: '973797524907',
    projectId: 'flwe-mobile-app-13052005',
    authDomain: 'flwe-mobile-app-13052005.firebaseapp.com',
    storageBucket: 'flwe-mobile-app-13052005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx0oyOPmIaKaVBzTPSm11uHhOLib4DIQw',
    appId: '1:973797524907:android:52d2c488685cd9ca637eee',
    messagingSenderId: '973797524907',
    projectId: 'flwe-mobile-app-13052005',
    storageBucket: 'flwe-mobile-app-13052005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqPbdvDUiV0uvCbb-Nlw_ScBtcXA6DEO4',
    appId: '1:973797524907:ios:a86bfd7920319be4637eee',
    messagingSenderId: '973797524907',
    projectId: 'flwe-mobile-app-13052005',
    storageBucket: 'flwe-mobile-app-13052005.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqPbdvDUiV0uvCbb-Nlw_ScBtcXA6DEO4',
    appId: '1:973797524907:ios:a86bfd7920319be4637eee',
    messagingSenderId: '973797524907',
    projectId: 'flwe-mobile-app-13052005',
    storageBucket: 'flwe-mobile-app-13052005.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALIxdIByssf5hkdxvDfeTz6todXh4zk58',
    appId: '1:973797524907:web:2e9cea5ff659e03d637eee',
    messagingSenderId: '973797524907',
    projectId: 'flwe-mobile-app-13052005',
    authDomain: 'flwe-mobile-app-13052005.firebaseapp.com',
    storageBucket: 'flwe-mobile-app-13052005.firebasestorage.app',
  );

}